### ISSUE TITLE
Add StarLight Network, Inc. as Hosting

### ISSUE THREAD

**Issue by alessandromrc** [calamity-inc/soup-extra-data#3]
This ISP should be added as Hosting:
https://ipinfo.io/AS214828

Also, noticed that when I edit the `release.wat` file inside the `build `folder it seems like the entire formatting gets heavily messed up when making a commit.

Am I doing something wrong or it's just the line endings being mixed up?

**Comment by Sainan** [comment]
Have a look at https://github.com/calamity-inc/soup-extra-data/blob/senpai/CONTRIBUTING.md

**Comment by alessandromrc** [comment]
> Have a look at https://github.com/calamity-inc/soup-extra-data/blob/senpai/CONTRIBUTING.md

Lmao, I never noticed the executable, thanks for letting me know haha... Should sleep I guess ;)
